<?xml version="1.0" encoding="iso-8859-1"?>
<TestCase>
  <UseCase>TEST_STEP_ENGINE</UseCase>
  <Description>Testing the functionality to loop over Test Steps and Test Step Sets.
    Error case : Test the error handling of a failure inside a loop.</Description>
  <TcExpectedResult>FAIL</TcExpectedResult>
  <b2bIteration>1</b2bIteration>
  <b2bContinuousMode>False</b2bContinuousMode>
  <Parameters>
    <Parameter>
      <Name>NB_ITER</Name>
      <Value>5</Value>
    </Parameter>
  </Parameters>
  <TestSteps>
    <Include Src="ACS_CI/TC/FWK/NOVAR/TESTSTEP/scripts/validsecondaryteststeptatalog.xml"/>
    <Setup/>
    <RunTest>
      <Loop Id="LoopFailure" Nb="5">
        <TestStep Id="DUMMY" RETURN_CODE="FAILURE" COMMENT="Dummy Error" INPUT_1="1" INPUT_2="2.63" CTX_DATA_1="DUMMY" CTX_DATA_2="BUNDLE"/>
        <TestStep Id="SUSPEND" DURATION_IN_SEC="1"/>
      </Loop>
    </RunTest>
    <TearDown/>
  </TestSteps>
</TestCase>
